### ISSUE TITLE
on credentials.py

### ISSUE THREAD

**Issue by ritvickguptaisb** [tanmay2298/Code_Fun_Do_PlusPlus#1]
Can you give me the outline for credentials.py?

**Comment by yashYRS** [comment]
Simply list all the values for all the variables used to connect to the online database, we had used Azure for our application. These values are made available when you log in and make a sql database on Azure.
A sample : 
""" credentials.py"""
driver = "somedriver"
server = "yourserver"
database = "databaseonazure"
username = "yourusername"
password = "yourpassword "
